spring.application.name=Billing

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/smartbill
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =====================================================
# WHATSAPP CLOUD API
# =====================================================

whatsapp.api-url=https://graph.facebook.com
#It must be an actual Graph API version supported by Meta.
whatsapp.api-version=vXX.X

# India country code
whatsapp.default-country-code=91

# Server
server.port=8083

# =========================================================
# RAZORPAY
# =========================================================

razorpay.key-id=rzp_test_xxxxxxxxxxxxx
razorpay.key-secret=xxxxxxxxxxxxxxxx
razorpay.webhook-secret=xxxxxxxxxxxxxxxx

# Razorpay Plan IDs
razorpay.monthly-plan-id=plan_xxxxxxxxxxxxx
razorpay.yearly-plan-id=plan_yyyyyyyyyyyyy
# Mock Email Config so app doesn't crash
spring.mail.host=localhost
spring.mail.port=2525
spring.mail.username=mock
spring.mail.password=mock
